version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    groups:
      payload:
        patterns: ['payload', '@payloadcms/*']
      next-react:
        patterns: ['next', 'eslint-config-next', 'react', 'react-dom', '@types/react*']
    ignore:
      - dependency-name: payload
        update-types: [version-update:semver-major]
      - dependency-name: '@payloadcms/*'
        update-types: [version-update:semver-major]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
