/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    sites: Site;
    'asset-classes': AssetClass;
    assets: Asset;
    'network-endpoints': NetworkEndpoint;
    'service-bindings': ServiceBinding;
    'asset-identifiers': AssetIdentifier;
    'asset-installations': AssetInstallation;
    'identity-cases': IdentityCase;
    'asset-imports': AssetImport;
    'asset-fields': AssetField;
    'user-roles': UserRole;
    users: User;
    'asset-observations': AssetObservation;
    'topology-links': TopologyLink;
    vulnerabilities: Vulnerability;
    'vulnerability-feeds': VulnerabilityFeed;
    'audit-logs': AuditLog;
    'worker-leases': WorkerLease;
    'worker-heartbeats': WorkerHeartbeat;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    sites: SitesSelect<false> | SitesSelect<true>;
    'asset-classes': AssetClassesSelect<false> | AssetClassesSelect<true>;
    assets: AssetsSelect<false> | AssetsSelect<true>;
    'network-endpoints': NetworkEndpointsSelect<false> | NetworkEndpointsSelect<true>;
    'service-bindings': ServiceBindingsSelect<false> | ServiceBindingsSelect<true>;
    'asset-identifiers': AssetIdentifiersSelect<false> | AssetIdentifiersSelect<true>;
    'asset-installations': AssetInstallationsSelect<false> | AssetInstallationsSelect<true>;
    'identity-cases': IdentityCasesSelect<false> | IdentityCasesSelect<true>;
    'asset-imports': AssetImportsSelect<false> | AssetImportsSelect<true>;
    'asset-fields': AssetFieldsSelect<false> | AssetFieldsSelect<true>;
    'user-roles': UserRolesSelect<false> | UserRolesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'asset-observations': AssetObservationsSelect<false> | AssetObservationsSelect<true>;
    'topology-links': TopologyLinksSelect<false> | TopologyLinksSelect<true>;
    vulnerabilities: VulnerabilitiesSelect<false> | VulnerabilitiesSelect<true>;
    'vulnerability-feeds': VulnerabilityFeedsSelect<false> | VulnerabilityFeedsSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'worker-leases': WorkerLeasesSelect<false> | WorkerLeasesSelect<true>;
    'worker-heartbeats': WorkerHeartbeatsSelect<false> | WorkerHeartbeatsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      'import-v1': TaskImportV1;
      'maintenance-v1': TaskMaintenanceV1;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Organize assets with your own site types and hierarchy.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites".
 */
export interface Site {
  id: string;
  name: string;
  type: string;
  /**
   * Optional parent site; nesting can be as deep as needed.
   */
  parent?: (string | null) | Site;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Define the classes assigned to OT assets.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "asset-classes".
 */
export interface AssetClass {
  id: string;
  name: string;
  description?: string | null;
  /**
   * Lower numbers are evaluated first when rules from multiple classes match an asset.
   */
  assignmentPriority: number;
  /**
   * Both case-insensitive regular expressions must match. Rules are evaluated in their displayed order.
   */
  assignmentRules?:
    | {
        manufacturerRegex: string;
        modelRegex: string;
        id?: string | null;
      }[]
    | null;
  legacyKey?: string | null;
  ruleSeedVersion?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Industrial devices, network endpoints, and control-system equipment.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assets".
 */
export interface Asset {
  id: string;
  identityRevision?: number | null;
  uuid?: string | null;
  physicalKind?: ('unknown' | 'device' | 'chassis' | 'module') | null;
  catalogNumber?: string | null;
  slotCapacity?: number | null;
  lifecycle?: ('active' | 'retired' | 'replaced' | 'merged') | null;
  baselined?: boolean | null;
  mergedInto?: (string | null) | Asset;
  replacedBy?: (string | null) | Asset;
  networkAddresses?:
    | {
        address: string;
        id?: string | null;
      }[]
    | null;
  networkMACs?:
    | {
        address: string;
        id?: string | null;
      }[]
    | null;
  name: string;
  description?: string | null;
  /**
   * The site or hierarchy node this asset belongs to.
   */
  site: string | Site;
  assetClass: string | AssetClass;
  assetOwner?: string | null;
  location?: string | null;
  customFields?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  fieldProvenance?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  assetType?: string | null;
  ipAddress?: string | null;
  macAddress?: string | null;
  networkMask?: string | null;
  gatewayAddress?: string | null;
  vendor?: string | null;
  model?: string | null;
  serialNumber?: string | null;
  operatingSystem?: string | null;
  /**
   * Confidence reported by the discovery source, from 0 to 100.
   */
  osAccuracy?: number | null;
  firmwareVersion?: string | null;
  hardwareVersion?: string | null;
  protocols?:
    | (
        | 'bacnet'
        | 'dnp3'
        | 'ethernet-ip'
        | 'iec61850'
        | 'modbus-tcp'
        | 'netbios'
        | 'niagara-fox'
        | 'omron-fins'
        | 'profinet'
        | 'opc-ua'
        | 's7'
        | 'other'
      )[]
    | null;
  status: 'online' | 'offline' | 'maintenance' | 'unknown';
  criticality: 'low' | 'medium' | 'high' | 'critical';
  /**
   * Unvalidated catalog matches for the recorded vendor, model, and version data. Empty until the vulnerability catalog is loaded.
   */
  vulnerabilityCount?: number | null;
  lastSeen?: string | null;
  importSource?: string | null;
  sourceVersion?: string | null;
  lastImportedAt?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "network-endpoints".
 */
export interface NetworkEndpoint {
  id: string;
  site: string | Site;
  asset?: (string | null) | Asset;
  bindingKey?: string | null;
  interfaceKey?: string | null;
  name?: string | null;
  macAddress?: string | null;
  addresses?:
    | {
        address: string;
        networkMask?: string | null;
        gatewayAddress?: string | null;
        id?: string | null;
      }[]
    | null;
  firstSeen: string;
  lastSeen?: string | null;
  endedAt?: string | null;
  reachability?: ('online' | 'offline' | 'unknown') | null;
  source?: string | null;
  fieldProvenance?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-bindings".
 */
export interface ServiceBinding {
  id: string;
  site: string | Site;
  asset?: (string | null) | Asset;
  endpoint: string | NetworkEndpoint;
  bindingKey?: string | null;
  address?: string | null;
  transport: 'tcp' | 'udp' | 'ethernet';
  port?: number | null;
  protocol: string;
  /**
   * Only record a route actually observed or explicitly supplied.
   */
  route?: string | null;
  firstSeen: string;
  lastSeen?: string | null;
  endedAt?: string | null;
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "asset-identifiers".
 */
export interface AssetIdentifier {
  id: string;
  site: string | Site;
  asset: string | Asset;
  key?: string | null;
  /**
   * Serial issuer namespace, e.g. cip, siemens, or a verified manufacturer namespace.
   */
  authority: string;
  manufacturer: string;
  scope: 'device' | 'chassis' | 'cpu' | 'adapter' | 'module';
  serial: string;
  productScope?: string | null;
  state: 'accepted' | 'contested' | 'revoked';
  source?: string | null;
  evidence?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "asset-installations".
 */
export interface AssetInstallation {
  id: string;
  site: string | Site;
  parent: string | Asset;
  module: string | Asset;
  /**
   * Leave empty when containment is known but slot position is not reported.
   */
  slotPath?: string | null;
  slotUUID?: string | null;
  activeSlot?: string | null;
  activeModule?: string | null;
  installedAt: string;
  removedAt?: string | null;
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "identity-cases".
 */
export interface IdentityCase {
  id: string;
  site: string | Site;
  asset?: (string | null) | Asset;
  candidate?: (string | null) | Asset;
  caseKey?: string | null;
  kind: 'identity-conflict' | 'possible-duplicate' | 'replacement' | 'cross-site';
  /**
   * Ordinal rule score, not a probability: 3 hardware, 2 endpoint, 1 heuristic, 0 unresolved.
   */
  confidence?: number | null;
  reason: string;
  evidence?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status: 'open' | 'resolved' | 'rejected';
  resolution?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Import physical identity and network evidence into a selected site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "asset-imports".
 */
export interface AssetImport {
  id: string;
  /**
   * Queued imports require deployed workers and OTSERVER_QUEUED_IMPORTS=on.
   */
  executionMode?: ('sync' | 'queued') | null;
  jobID?: string | null;
  submittedBy?: string | null;
  executorID?: string | null;
  retriedBy?: string | null;
  fileDigest?: string | null;
  processingInput?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  queuedAt?: string | null;
  startedAt?: string | null;
  completedAt?: string | null;
  attemptCount?: number | null;
  appliedKey?: string | null;
  duplicateOf?: (string | null) | AssetImport;
  /**
   * Every asset in this file will be assigned to this site.
   */
  site: string | Site;
  source: 'otserver-otter' | 'proneta' | 'nmap';
  /**
   * Optional values overwrite these fields on every new or existing asset in this import.
   */
  assetOverrides?: {
    assetOwner?: string | null;
    location?: string | null;
  };
  customFieldOverrides?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  sourceVersion: string;
  status: 'pending' | 'running' | 'completed' | 'failed';
  createdAssets?: number | null;
  updatedAssets?: number | null;
  skippedAssets?: number | null;
  projectName?: string | null;
  topologyName?: string | null;
  warnings?: string | null;
  scanMetadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  unresolved?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  error?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Define optional fields that appear on every asset and import.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "asset-fields".
 */
export interface AssetField {
  id: string;
  label: string;
  /**
   * The type is fixed after this field is created.
   */
  type: 'text' | 'textarea' | 'number' | 'checkbox' | 'date';
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Assign read or write access to a site and every site underneath it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-roles".
 */
export interface UserRole {
  id: string;
  name: string;
  /**
   * The permanent Admin role has unrestricted access.
   */
  isAdmin?: boolean | null;
  /**
   * Each permission applies to the selected site and all descendants.
   */
  permissions?:
    | {
        site: string | Site;
        access: 'read' | 'read-write';
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  role: string | UserRole;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  hasAPIKey?: boolean | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "asset-observations".
 */
export interface AssetObservation {
  id: string;
  site: string | Site;
  asset: string | Asset;
  import: string | AssetImport;
  source: string;
  endpoint?: (string | null) | NetworkEndpoint;
  identityEvidence?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  quality: 'high' | 'medium' | 'low';
  observedAt: string;
  fields:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  interfaces?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  ports?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  raw?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  warnings?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topology-links".
 */
export interface TopologyLink {
  id: string;
  site: string | Site;
  import: string | AssetImport;
  localAsset?: (string | null) | Asset;
  remoteAsset?: (string | null) | Asset;
  source: string;
  observedAt: string;
  local:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  remote:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  raw?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Downloaded NVD, CSAF, CISA KEV, and ICS Advisory Project entries used for passive asset matching.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vulnerabilities".
 */
export interface Vulnerability {
  id: string;
  cve: string;
  description?: string | null;
  cvssScore?: number | null;
  cvssSeverity?: string | null;
  status?: string | null;
  published?: string | null;
  modified?: string | null;
  references?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  affected?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  vendors?: string[] | null;
  products?: string[] | null;
  productTokens?: string[] | null;
  knownExploited?: boolean | null;
  kevDateAdded?: string | null;
  kevDueDate?: string | null;
  kevName?: string | null;
  kevProduct?: string | null;
  kevRequiredAction?: string | null;
  kevRansomwareUse?: string | null;
  kevVendor?: string | null;
  icsAdvisory?: string[] | null;
  icsSectors?: string[] | null;
  icsDistribution?: string | null;
  icsHeadquarters?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Synchronization state of the downloaded vulnerability catalogs.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vulnerability-feeds".
 */
export interface VulnerabilityFeed {
  id: string;
  source: string;
  status: 'idle' | 'running' | 'ready' | 'partial' | 'failed';
  lastSyncedAt?: string | null;
  documentCount?: number | null;
  catalogVersion?: string | null;
  dateReleased?: string | null;
  error?: string | null;
  state?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Immutable history of inventory, configuration, and authentication changes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: string;
  site?: (string | null) | Site;
  summary: string;
  action: 'create' | 'update' | 'delete' | 'login' | 'logout' | 'custom';
  targetCollection: string;
  documentID?: string | null;
  documentLabel?: string | null;
  asset?: (string | null) | Asset;
  assetID?: string | null;
  actorType: 'user' | 'system';
  actorID?: string | null;
  actorName?: string | null;
  actorEmail?: string | null;
  ipAddress?: string | null;
  requestMethod?: string | null;
  requestPath?: string | null;
  changes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "worker-leases".
 */
export interface WorkerLease {
  id: string;
  queue: string;
  owner: string;
  revision?: number | null;
  lastSuccessAt?: string | null;
  lastJobID?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "worker-heartbeats".
 */
export interface WorkerHeartbeat {
  id: string;
  queue: string;
  owner: string;
  heartbeatAt: string;
  expiresAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'import-v1' | 'maintenance-v1';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'import-v1' | 'maintenance-v1') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'sites';
        value: string | Site;
      } | null)
    | ({
        relationTo: 'asset-classes';
        value: string | AssetClass;
      } | null)
    | ({
        relationTo: 'assets';
        value: string | Asset;
      } | null)
    | ({
        relationTo: 'network-endpoints';
        value: string | NetworkEndpoint;
      } | null)
    | ({
        relationTo: 'service-bindings';
        value: string | ServiceBinding;
      } | null)
    | ({
        relationTo: 'asset-identifiers';
        value: string | AssetIdentifier;
      } | null)
    | ({
        relationTo: 'asset-installations';
        value: string | AssetInstallation;
      } | null)
    | ({
        relationTo: 'identity-cases';
        value: string | IdentityCase;
      } | null)
    | ({
        relationTo: 'asset-imports';
        value: string | AssetImport;
      } | null)
    | ({
        relationTo: 'asset-fields';
        value: string | AssetField;
      } | null)
    | ({
        relationTo: 'user-roles';
        value: string | UserRole;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'worker-leases';
        value: string | WorkerLease;
      } | null)
    | ({
        relationTo: 'worker-heartbeats';
        value: string | WorkerHeartbeat;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites_select".
 */
export interface SitesSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  parent?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "asset-classes_select".
 */
export interface AssetClassesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  assignmentPriority?: T;
  assignmentRules?:
    | T
    | {
        manufacturerRegex?: T;
        modelRegex?: T;
        id?: T;
      };
  legacyKey?: T;
  ruleSeedVersion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assets_select".
 */
export interface AssetsSelect<T extends boolean = true> {
  identityRevision?: T;
  uuid?: T;
  physicalKind?: T;
  catalogNumber?: T;
  slotCapacity?: T;
  lifecycle?: T;
  baselined?: T;
  mergedInto?: T;
  replacedBy?: T;
  networkAddresses?:
    | T
    | {
        address?: T;
        id?: T;
      };
  networkMACs?:
    | T
    | {
        address?: T;
        id?: T;
      };
  name?: T;
  description?: T;
  site?: T;
  assetClass?: T;
  assetOwner?: T;
  location?: T;
  customFields?: T;
  fieldProvenance?: T;
  assetType?: T;
  ipAddress?: T;
  macAddress?: T;
  networkMask?: T;
  gatewayAddress?: T;
  vendor?: T;
  model?: T;
  serialNumber?: T;
  operatingSystem?: T;
  osAccuracy?: T;
  firmwareVersion?: T;
  hardwareVersion?: T;
  protocols?: T;
  status?: T;
  criticality?: T;
  vulnerabilityCount?: T;
  lastSeen?: T;
  importSource?: T;
  sourceVersion?: T;
  lastImportedAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "network-endpoints_select".
 */
export interface NetworkEndpointsSelect<T extends boolean = true> {
  site?: T;
  asset?: T;
  bindingKey?: T;
  interfaceKey?: T;
  name?: T;
  macAddress?: T;
  addresses?:
    | T
    | {
        address?: T;
        networkMask?: T;
        gatewayAddress?: T;
        id?: T;
      };
  firstSeen?: T;
  lastSeen?: T;
  endedAt?: T;
  reachability?: T;
  source?: T;
  fieldProvenance?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-bindings_select".
 */
export interface ServiceBindingsSelect<T extends boolean = true> {
  site?: T;
  asset?: T;
  endpoint?: T;
  bindingKey?: T;
  address?: T;
  transport?: T;
  port?: T;
  protocol?: T;
  route?: T;
  firstSeen?: T;
  lastSeen?: T;
  endedAt?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "asset-identifiers_select".
 */
export interface AssetIdentifiersSelect<T extends boolean = true> {
  site?: T;
  asset?: T;
  key?: T;
  authority?: T;
  manufacturer?: T;
  scope?: T;
  serial?: T;
  productScope?: T;
  state?: T;
  source?: T;
  evidence?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "asset-installations_select".
 */
export interface AssetInstallationsSelect<T extends boolean = true> {
  site?: T;
  parent?: T;
  module?: T;
  slotPath?: T;
  slotUUID?: T;
  activeSlot?: T;
  activeModule?: T;
  installedAt?: T;
  removedAt?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "identity-cases_select".
 */
export interface IdentityCasesSelect<T extends boolean = true> {
  site?: T;
  asset?: T;
  candidate?: T;
  caseKey?: T;
  kind?: T;
  confidence?: T;
  reason?: T;
  evidence?: T;
  status?: T;
  resolution?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "asset-imports_select".
 */
export interface AssetImportsSelect<T extends boolean = true> {
  executionMode?: T;
  jobID?: T;
  submittedBy?: T;
  executorID?: T;
  retriedBy?: T;
  fileDigest?: T;
  processingInput?: T;
  queuedAt?: T;
  startedAt?: T;
  completedAt?: T;
  attemptCount?: T;
  appliedKey?: T;
  duplicateOf?: T;
  site?: T;
  source?: T;
  assetOverrides?:
    | T
    | {
        assetOwner?: T;
        location?: T;
      };
  customFieldOverrides?: T;
  sourceVersion?: T;
  status?: T;
  createdAssets?: T;
  updatedAssets?: T;
  skippedAssets?: T;
  projectName?: T;
  topologyName?: T;
  warnings?: T;
  scanMetadata?: T;
  unresolved?: T;
  error?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "asset-fields_select".
 */
export interface AssetFieldsSelect<T extends boolean = true> {
  label?: T;
  type?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-roles_select".
 */
export interface UserRolesSelect<T extends boolean = true> {
  name?: T;
  isAdmin?: T;
  permissions?:
    | T
    | {
        site?: T;
        access?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  hasAPIKey?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "asset-observations_select".
 */
export interface AssetObservationsSelect<T extends boolean = true> {
  site?: T;
  asset?: T;
  import?: T;
  source?: T;
  endpoint?: T;
  identityEvidence?: T;
  quality?: T;
  observedAt?: T;
  fields?: T;
  interfaces?: T;
  ports?: T;
  raw?: T;
  warnings?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topology-links_select".
 */
export interface TopologyLinksSelect<T extends boolean = true> {
  site?: T;
  import?: T;
  localAsset?: T;
  remoteAsset?: T;
  source?: T;
  observedAt?: T;
  local?: T;
  remote?: T;
  raw?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vulnerabilities_select".
 */
export interface VulnerabilitiesSelect<T extends boolean = true> {
  cve?: T;
  description?: T;
  cvssScore?: T;
  cvssSeverity?: T;
  status?: T;
  published?: T;
  modified?: T;
  references?: T;
  affected?: T;
  vendors?: T;
  products?: T;
  productTokens?: T;
  knownExploited?: T;
  kevDateAdded?: T;
  kevDueDate?: T;
  kevName?: T;
  kevProduct?: T;
  kevRequiredAction?: T;
  kevRansomwareUse?: T;
  kevVendor?: T;
  icsAdvisory?: T;
  icsSectors?: T;
  icsDistribution?: T;
  icsHeadquarters?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vulnerability-feeds_select".
 */
export interface VulnerabilityFeedsSelect<T extends boolean = true> {
  source?: T;
  status?: T;
  lastSyncedAt?: T;
  documentCount?: T;
  catalogVersion?: T;
  dateReleased?: T;
  error?: T;
  state?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  site?: T;
  summary?: T;
  action?: T;
  targetCollection?: T;
  documentID?: T;
  documentLabel?: T;
  asset?: T;
  assetID?: T;
  actorType?: T;
  actorID?: T;
  actorName?: T;
  actorEmail?: T;
  ipAddress?: T;
  requestMethod?: T;
  requestPath?: T;
  changes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "worker-leases_select".
 */
export interface WorkerLeasesSelect<T extends boolean = true> {
  queue?: T;
  owner?: T;
  revision?: T;
  lastSuccessAt?: T;
  lastJobID?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "worker-heartbeats_select".
 */
export interface WorkerHeartbeatsSelect<T extends boolean = true> {
  queue?: T;
  owner?: T;
  heartbeatAt?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskImport-v1".
 */
export interface TaskImportV1 {
  input: {
    version: number;
    importID: string;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskMaintenance-v1".
 */
export interface TaskMaintenanceV1 {
  input: {
    version: number;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}