/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    sites: Site;
    'asset-classes': AssetClass;
    assets: Asset;
    'asset-imports': AssetImport;
    'asset-fields': AssetField;
    'user-roles': UserRole;
    users: User;
    'asset-observations': AssetObservation;
    'topology-links': TopologyLink;
    'audit-logs': AuditLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    sites: SitesSelect<false> | SitesSelect<true>;
    'asset-classes': AssetClassesSelect<false> | AssetClassesSelect<true>;
    assets: AssetsSelect<false> | AssetsSelect<true>;
    'asset-imports': AssetImportsSelect<false> | AssetImportsSelect<true>;
    'asset-fields': AssetFieldsSelect<false> | AssetFieldsSelect<true>;
    'user-roles': UserRolesSelect<false> | UserRolesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'asset-observations': AssetObservationsSelect<false> | AssetObservationsSelect<true>;
    'topology-links': TopologyLinksSelect<false> | TopologyLinksSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Organize assets with your own site types and hierarchy.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites".
 */
export interface Site {
  id: string;
  name: string;
  type: string;
  /**
   * Optional parent site; nesting can be as deep as needed.
   */
  parent?: (string | null) | Site;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Define the classes assigned to OT assets.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "asset-classes".
 */
export interface AssetClass {
  id: string;
  name: string;
  description?: string | null;
  /**
   * Lower numbers are evaluated first when rules from multiple classes match an asset.
   */
  assignmentPriority: number;
  /**
   * Both case-insensitive regular expressions must match. Rules are evaluated in their displayed order.
   */
  assignmentRules?:
    | {
        manufacturerRegex: string;
        modelRegex: string;
        id?: string | null;
      }[]
    | null;
  legacyKey?: string | null;
  ruleSeedVersion?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Industrial devices, network endpoints, and control-system equipment.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assets".
 */
export interface Asset {
  id: string;
  name: string;
  description?: string | null;
  /**
   * The site or hierarchy node this asset belongs to.
   */
  site: string | Site;
  assetClass: string | AssetClass;
  assetOwner?: string | null;
  location?: string | null;
  customFields?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  fieldProvenance?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  assetType?: string | null;
  ipAddress?: string | null;
  macAddress: string;
  networkMask?: string | null;
  gatewayAddress?: string | null;
  vendor?: string | null;
  model?: string | null;
  serialNumber?: string | null;
  operatingSystem?: string | null;
  /**
   * Confidence reported by the discovery source, from 0 to 100.
   */
  osAccuracy?: number | null;
  firmwareVersion?: string | null;
  protocols?:
    | (
        'bacnet' | 'ethernet-ip' | 'modbus-tcp' | 'niagara-fox' | 'omron-fins' | 'profinet' | 'opc-ua' | 's7' | 'other'
      )[]
    | null;
  status: 'online' | 'offline' | 'maintenance' | 'unknown';
  criticality: 'low' | 'medium' | 'high' | 'critical';
  lastSeen?: string | null;
  importSource?: string | null;
  sourceVersion?: string | null;
  lastImportedAt?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * Upload discovery files to create or update assets by MAC address.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "asset-imports".
 */
export interface AssetImport {
  id: string;
  /**
   * Every asset in this file will be assigned to this site.
   */
  site: string | Site;
  source: 'otserver-otter' | 'proneta' | 'nmap';
  /**
   * Optional values overwrite these fields on every new or existing asset in this import.
   */
  assetOverrides?: {
    assetOwner?: string | null;
    location?: string | null;
  };
  customFieldOverrides?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  sourceVersion: string;
  status: 'pending' | 'completed' | 'failed';
  createdAssets?: number | null;
  updatedAssets?: number | null;
  skippedAssets?: number | null;
  projectName?: string | null;
  topologyName?: string | null;
  warnings?: string | null;
  scanMetadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  unresolved?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  error?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Define optional fields that appear on every asset and import.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "asset-fields".
 */
export interface AssetField {
  id: string;
  label: string;
  /**
   * The type is fixed after this field is created.
   */
  type: 'text' | 'textarea' | 'number' | 'checkbox' | 'date';
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Assign read or write access to a site and every site underneath it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-roles".
 */
export interface UserRole {
  id: string;
  name: string;
  /**
   * The permanent Admin role has unrestricted access.
   */
  isAdmin?: boolean | null;
  /**
   * Each permission applies to the selected site and all descendants.
   */
  permissions?:
    | {
        site: string | Site;
        access: 'read' | 'read-write';
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  role: string | UserRole;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "asset-observations".
 */
export interface AssetObservation {
  id: string;
  site: string | Site;
  asset: string | Asset;
  import: string | AssetImport;
  source: string;
  quality: 'high' | 'medium' | 'low';
  observedAt: string;
  fields:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  interfaces?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  ports?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  raw?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  warnings?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topology-links".
 */
export interface TopologyLink {
  id: string;
  site: string | Site;
  import: string | AssetImport;
  localAsset?: (string | null) | Asset;
  remoteAsset?: (string | null) | Asset;
  source: string;
  observedAt: string;
  local:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  remote:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  raw?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Immutable history of inventory, configuration, and authentication changes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: string;
  summary: string;
  action: 'create' | 'update' | 'delete' | 'login' | 'logout' | 'custom';
  targetCollection: string;
  documentID?: string | null;
  documentLabel?: string | null;
  asset?: (string | null) | Asset;
  assetID?: string | null;
  actorType: 'user' | 'system';
  actorID?: string | null;
  actorName?: string | null;
  actorEmail?: string | null;
  ipAddress?: string | null;
  requestMethod?: string | null;
  requestPath?: string | null;
  changes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'sites';
        value: string | Site;
      } | null)
    | ({
        relationTo: 'asset-classes';
        value: string | AssetClass;
      } | null)
    | ({
        relationTo: 'assets';
        value: string | Asset;
      } | null)
    | ({
        relationTo: 'asset-imports';
        value: string | AssetImport;
      } | null)
    | ({
        relationTo: 'asset-fields';
        value: string | AssetField;
      } | null)
    | ({
        relationTo: 'user-roles';
        value: string | UserRole;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites_select".
 */
export interface SitesSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  parent?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "asset-classes_select".
 */
export interface AssetClassesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  assignmentPriority?: T;
  assignmentRules?:
    | T
    | {
        manufacturerRegex?: T;
        modelRegex?: T;
        id?: T;
      };
  legacyKey?: T;
  ruleSeedVersion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assets_select".
 */
export interface AssetsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  site?: T;
  assetClass?: T;
  assetOwner?: T;
  location?: T;
  customFields?: T;
  fieldProvenance?: T;
  assetType?: T;
  ipAddress?: T;
  macAddress?: T;
  networkMask?: T;
  gatewayAddress?: T;
  vendor?: T;
  model?: T;
  serialNumber?: T;
  operatingSystem?: T;
  osAccuracy?: T;
  firmwareVersion?: T;
  protocols?: T;
  status?: T;
  criticality?: T;
  lastSeen?: T;
  importSource?: T;
  sourceVersion?: T;
  lastImportedAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "asset-imports_select".
 */
export interface AssetImportsSelect<T extends boolean = true> {
  site?: T;
  source?: T;
  assetOverrides?:
    | T
    | {
        assetOwner?: T;
        location?: T;
      };
  customFieldOverrides?: T;
  sourceVersion?: T;
  status?: T;
  createdAssets?: T;
  updatedAssets?: T;
  skippedAssets?: T;
  projectName?: T;
  topologyName?: T;
  warnings?: T;
  scanMetadata?: T;
  unresolved?: T;
  error?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "asset-fields_select".
 */
export interface AssetFieldsSelect<T extends boolean = true> {
  label?: T;
  type?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-roles_select".
 */
export interface UserRolesSelect<T extends boolean = true> {
  name?: T;
  isAdmin?: T;
  permissions?:
    | T
    | {
        site?: T;
        access?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "asset-observations_select".
 */
export interface AssetObservationsSelect<T extends boolean = true> {
  site?: T;
  asset?: T;
  import?: T;
  source?: T;
  quality?: T;
  observedAt?: T;
  fields?: T;
  interfaces?: T;
  ports?: T;
  raw?: T;
  warnings?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topology-links_select".
 */
export interface TopologyLinksSelect<T extends boolean = true> {
  site?: T;
  import?: T;
  localAsset?: T;
  remoteAsset?: T;
  source?: T;
  observedAt?: T;
  local?: T;
  remote?: T;
  raw?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  summary?: T;
  action?: T;
  targetCollection?: T;
  documentID?: T;
  documentLabel?: T;
  asset?: T;
  assetID?: T;
  actorType?: T;
  actorID?: T;
  actorName?: T;
  actorEmail?: T;
  ipAddress?: T;
  requestMethod?: T;
  requestPath?: T;
  changes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}